version: '3'
services:
  app:
    build: .
    container_name: onlineStore
    ports:
      - "8080:8080"
    depends_on:
      - db
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/onlineStore
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379

  db:
    image: postgres:13
    container_name: onlineStore-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=onlineStore
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    container_name: onlineStore-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: